-- MySQL Script generated by MySQL Workbench
-- vie 10 abr 2020 23:30:54 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lista_tareas_vue
-- -----------------------------------------------------
-- Base de datos ya una lista de tareas hecha en vuejs

-- -----------------------------------------------------
-- Schema lista_tareas_vue
--
-- Base de datos ya una lista de tareas hecha en vuejs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lista_tareas_vue` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `lista_tareas_vue` ;

-- -----------------------------------------------------
-- Table `lista_tareas_vue`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_tareas_vue`.`tareas` (
  `idTareas` INT NOT NULL AUTO_INCREMENT,
  `nombreTarea` VARCHAR(50) NOT NULL COMMENT 'Nombre de la tarea',
  `fecha` VARCHAR(45) NOT NULL COMMENT 'fecha en cuando se tiene planeado empezar la tarea',
  PRIMARY KEY (`idTareas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci
COMMENT = 'tabla donde se almacenaran las tareas';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
